### ISSUE TITLE
Cargo workspace support.

### ISSUE THREAD

**Issue by martinfrances107** [Keruspe/cargo-duplicates#7]
It looks like parsing of Cargo.toml files in the context of workspaces does not work.

That is parsing  does not yet support workspaces.

when I supply a valid Cargo.toml file ( cargo check report the definitions are valid ) 

BUT I make reference to values listed in the root workspace as follows 

```toml
 authors = { workspace = true }
 categories = { workspace = true }
 edition = { workspace = true }
```

Then I see errors like this

Caused by:
  failed to parse manifest at `XX/rust_d3_geo/examples/globe/canvas/Cargo.toml`

Caused by:
  invalid type: map, expected a sequence for key `package.authors`
